name: Main Branch Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github

    - name: Get version from pom.xml
      id: get-version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Detected version: $VERSION"

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Run tests
      run: mvn test

    - name: Generate test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: target/surefire-reports/*.xml
        reporter: java-junit

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get-version.outputs.version }}
        name: Release v${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          target/*.jar
          target/*.war
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
